### ISSUE TITLE
Wide lens camera not showing

### ISSUE THREAD

**Issue by MohamedAliClai** [HelgeApps/dual_camera_video_recorder_faq#1]
Hi
On your other app "background video recorder" the wide lens camera is showing
But in dual camera app id doesn't show in the same device
Is there a way to get the wide lens camera in dual camera app
My device is Xiaomi pofo f6
Thanks

**Comment by HelgeApps** [comment]
If zoom out doesn't work from 1x to 0.6x then the manufacture doesn't support it in dual mode. It's possible with Samsung of S series for example or Pixel
